name: book_rental_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  # plugin for adapting screen and font size
  flutter_screenutil: ^5.9.3
  # SVG rendering and widget library for Flutter
  flutter_svg: ^2.1.0
  device_preview: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  
  assets:
    - assets/svg/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
          
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

    - family: Apple
      fonts:
        - asset: assets/fonts/Apple.ttf
        
        
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
