// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa3QmYTjrJ9tbmmANvb1my_j_7M8AUF3A',
    appId: '1:700905090685:web:aee3bb9f7e6e6c43820b14',
    messagingSenderId: '700905090685',
    projectId: 'book-app-65015',
    authDomain: 'book-app-65015.firebaseapp.com',
    storageBucket: 'book-app-65015.firebasestorage.app',
    measurementId: 'G-FB20VPW9J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVp4nR0NNfYa-xUrxnm9CMxrtEw9pnnt4',
    appId: '1:700905090685:android:2121c8639143bf9f820b14',
    messagingSenderId: '700905090685',
    projectId: 'book-app-65015',
    storageBucket: 'book-app-65015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjdisuQ7PzLkXQG_Y3olUqGHiE8r2U2w4',
    appId: '1:700905090685:ios:24321e8c109a8de2820b14',
    messagingSenderId: '700905090685',
    projectId: 'book-app-65015',
    storageBucket: 'book-app-65015.firebasestorage.app',
    iosBundleId: 'com.example.bookRentalApp',
  );
}
